# Theme Settings
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dirt"

# Site Settings
locale: "en-US"
title: "Spacebar"
logo: "/assets/images/logo-cropped.png"
title_separator: "-"
name: "Spacebar"
description: "Principal engineering and leadership consulting."
domain: "mikepack.github.io"
url: "mikepack.github.io"
baseurl: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Mike Pack"
  avatar: "/assets/images/headshot.png"
  bio: "Howdy! I'm a principal engineer and senior startup leader with a passion for building, innovating, and solving tough challenges. This is a glimpse into my brain."
  location: "Denver, CO"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github" 
      url: "https://github.com/mikepack"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mikepackdev/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mike@spacebar.dev"

# Build settings
include: ["_pages"]
tag_archive:
  type: liquid
  path: /tags/

collections:
  archives:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: false
      classes: wide
      show_date: true
      tag_archive: true
      sort_by: date
      sort_order: reverse
  - scope:
      path: ""
      type: archives
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      classes: wide
      show_date: true
      tag_archive: true
      sort_by: date
      sort_order: reverse
  - scope:
      path: ""
      type: contact
    values:
      layout: single
      author_profile: true
      classes: wide


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mikepack"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mikepackdev/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mike@spacebar.dev"
